name: sample code for build java project

on: push
   
jobs:
  Initialise:
    runs-on: ubuntu-latest
    steps: 
      - name: ouput github context
        run: echo "${{ toJSON(github.event) }}"
      

  
  
          

  

    

