name: sample code for build java project

on: push
   
jobs:
  Initialise:
    runs-on: ubuntu-latest
    outputs:
       script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: checkout code
        uses: actions/checkout@v3.3.0
      - name: Setup Java JDK
        uses: actions/setup-java@v3.10.0
        with:
         distribution: 'zulu'
         java-version: '11'
         java-package: jdk
      - name: check java version
        run: java --version
        
      - name: build job
        run: maven package 
      - name: publishfiles
        id: publish
        run: find simple-java-maven-app/src/test/java/com/mycompany/app/*.java -type f -execdir echo '::set-output name=script-file::{}' ';'

  
  
          

  

    

