name: sample code for build java project

on: push
   
jobs:
  Initialise:
    runs-on: ubuntu-latest
    outputs:
       script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn package
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
            name: artifact
            path: target/my-app-1.0-SNAPSHOT.jar
      - name: publishfiles
        id: publish
        run: find simple-java-maven-app/src/test/java/com/mycompany/app/*.java -type f -execdir echo '::set-output name=script-file::{}' ';'
  deploy:
    needs: Initialise
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.2
        with:
         name: artifact
      - name: output filename
        run: echo "${{ needs.Initialise.outputs.script-file}}"
         
