name: sample code for build java project

on: push
   
jobs:
  Initialise:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn package
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
            name: artifact
            path: target/my-app-1.0-SNAPSHOT.jar
  deploy:
    needs: Initialise
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.2
        with:
    # Artifact name
          name: artifact
    # Destination path
  
         
      

  
  
          

  

    

